name: Compilar y desplegar
on:
  workflow_dispatch:
  push:
    paths:
      - 'GithubActionsDemoApp/**'
      - '.github/workflows/main.yml'    
      - 'Pruebas/**'
    branches:
      - main

jobs:
    builds:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        env:
            proyecto: GithubActionsDemoApp/GithubActionsDemoApp.csproj
            
        steps: 
            - name: Checkout
              uses: actions/checkout@v2

            - name: Instalar .NET
              uses: actions/setup-dotnet@v4.1.0
              with:
                    dotnet-version: 8.0.x

            - name: Obteniendo dependencias
              run: dotnet restore
              
            - name: Compilando
              run: dotnet build --no-restore

            - name: Ejecutando pruebas
              run: dotnet test --no-build

            - name: Publicando
              run: dotnet publish $proyecto -c Release -o miapp --runtime win-x86

            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v4.4.3
              with:
                path: ./miapp
                name: build

            - name: Desplegando zip
              run: zip -r miapp.zip ./miapp

            - name: Relase
              uses: softprops/action-gh-release@v2.0.9
              with:
                files: ./miapp.zip
                body: "Release de la aplicación"
                tag_name: ${{ github.ref_name }} 